### PR TITLE
feat:92-implement-no-search-found

### LINKED ISSUE #92: [FEAT] External Dynamic Pages > Career Page > Implement no search found
## Description
Develop a component to display when no search results match the user's search criteria. This component should provide clear feedback and guidance to users.

## Acceptance Criteria

- The component displays an appropriate illustration and message when no results are found.
- The component is responsive and displays correctly on all screen sizes.
- The message is clear and provides helpful next steps for the user.

### Requirements	
The "no search found" component should include:
- An illustrative graphic representing the absence of search results.
- A primary message indicating no search results available.
- A secondary message encouraging users to try another Job.

###  Tasks

- Design the "no search found" component based on the provided example and requirements.
- source an appropriate illustrative graphic
- Write the primary and secondary messages, focusing on clarity and user guidance.
- Implement any animations or transitions for smooth appearance/disappearance of the component.

# LINKS

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1553-43136&m=dev).

# IMAGES

image

### PR DESCRIPTION
**Pull request by Azikenp**
# Feature 92: Implement no search found 

**Closes #92

## I implemented the no search found component

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

lint pass

### CODE REVIEW

**Comment by psalm987** [comment]
Uhhh... the screenshot doesn't correspond to the task, Please review

**Comment by Azikenp** [comment]
Capture

**Comment by Azikenp** [comment]
> Uhhh... the screenshot doesn't correspond to the task and no figma link, Please review

what changes do you want?

**Review by shalomtaiwo — APPROVED** [review]

**Pull request merged**
