### PR TITLE
Implement the organization sign up page as shown in the design for issue #15 

### PR DESCRIPTION
**Pull request by itsAakashz**
# Description

**Closes #issue_number_here**
15
# Changes proposed

## What were you told to do?
I have told to Implement the organization sign up page as shown in the design for issue #15 

Authentication Page -> Sign up Organization

## What did you do?
This PR adds a signup form for creating an organization account. It includes the following changes:

Form Fields and Validation:

Created an interface FormData to define the types for the form fields.
Added an interface FormErrors to handle validation error messages.
Implemented the validateForm function to validate form data and return error messages if fields are missing or incorrect.
Added a client-side validation for the email field to remove errors as the user types.
Form Components:

Used Form, Label, Input, and Button components from @remix-run/react and custom components for UI elements.
Created a responsive form layout with various input fields such as company name, email, industry, organization type, country, state, address, and LGA.
Form Submission Handling:

Implemented the handleSubmit function to validate the form data before submission.
Used the useActionData hook to handle server-side validation errors and display them on the form.
Styling:

Applied conditional styling to input fields to indicate validation states.
Ensured the form is responsive and user-friendly on both desktop and mobile devices.

I created OrganizationSignUpPage.tsx inside Route folder

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

snap
mobile

### CODE REVIEW

**Comment by chumex412** [comment]
You implementation is different from design and no screenshot of mobile view

**Comment by itsAakashz** [comment]
I have updated mobile screenshot and still there no footer and header components so i did't included. There was so much confusion about everything so i came up with this design and it matches so much to design in figma.

**Comment by psalm987** [comment]
The header and footer have been added. Implement and make updates.

**Comment by itsAakashz** [comment]
i implemented header and footer in my last commit

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
Firstly  what is the space doing between the navbar and the signUp.

Also, what is going on with the padding???

image

**Review by shalomtaiwo — APPROVED** [review]

**Pull request merged**
