### PR TITLE
[FEAT] COMPONENTS: Side Navigation bar (MOBILE) 

### PR DESCRIPTION
**Pull request by ikennarichard**
## [FEAT] COMPONENTS: Side Navigation bar (MOBILE)

For this project I implemented the following features:
- Added responsive sidebar component.
- Implemented dark mode and light mode styles.
- Added toggle button for dark mode/light mode.
- Styled sidebar to highlight the active menu item.
- Ensured compliance with brand design guidelines.
- [Issue](https://github.com/hngprojects/hng_boilerplate_remix/issues/5)
- [Dev Mode Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2202-24512&t=nX0WeNz2MtrDAEes-0)
- lint-result
- sidebar-snapshot-1-dark
- sidebar-snapshot-1-light
- sidebar-snapshot-2-light
- sidebar-snapshot-2-dark
- snapshot3-close
- snapshot3-open

### CODE REVIEW

**Comment by ikennarichard** [comment]
@chumex412 let me change and request a review

**Comment by chumex412** [comment]
Hold on, just leave it like that

**Comment by chumex412** [comment]
Just ensure to remove the package-lock file

**Comment by ikennarichard** [comment]
I didn't see your earlier messages, just added a new commit @chumex412

**Review by chumex412 — CHANGES_REQUESTED** [review]
Why are you working on the sidebar for mobile?

The person that implemented the desktop version should have implemented the one for mobile screens

**Comment by ikennarichard** [comment]
it was issue number #5?

**Comment by chumex412** [comment]
Yes, I know but it is one whole task it shouldn't be separate

**Comment by ikennarichard** [comment]
You think we should invite a mentor?

**Comment by ikennarichard** [comment]
@chumex412 I've removed both lock files

**Comment by ikennarichard** [comment]
@chumex412 Please you can review, I've made necessary changes

**Comment by psalm987** [comment]
Please check the design for updates and make the required changes, then send updated screenshots... Don't worry about the background colour for now, the theme maintainers will handle that:

- The theme-switching icons were removed
- Your submission did not include variants with profile and sign-in information below.

Mobile side bar

**Comment by ikennarichard** [comment]
@psalm987 ok, im on it

**Comment by ikennarichard** [comment]
@psalm987 please check now, I've added the changes

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
Why can the mobile nav scroll with the rest of the pages.

If it's a sidenav like this, it should be fixed and not affect the structure of the page either.

When on mobile, how would I view my full page if the mobile nav is covering a bit of the main content.

image

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
check for conflicts

**Comment by ikennarichard** [comment]
@shalomtaiwo ok thank you

**Comment by ikennarichard** [comment]
@shalomtaiwo I've corrected the conflicts

**Review by mrcoded — APPROVED** [review]

**Pull request merged**
